# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwtable2csv.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 538)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("table.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.ctrlWidget = QtWidgets.QWidget(MainWindow)
        self.ctrlWidget.setObjectName("ctrlWidget")
        self.gbxConexionBD = QtWidgets.QGroupBox(self.ctrlWidget)
        self.gbxConexionBD.setGeometry(QtCore.QRect(20, 10, 491, 151))
        self.gbxConexionBD.setObjectName("gbxConexionBD")
        self.ledServidor = QtWidgets.QLineEdit(self.gbxConexionBD)
        self.ledServidor.setGeometry(QtCore.QRect(130, 20, 331, 20))
        self.ledServidor.setObjectName("ledServidor")
        self.ledBD = QtWidgets.QLineEdit(self.gbxConexionBD)
        self.ledBD.setGeometry(QtCore.QRect(130, 50, 171, 20))
        self.ledBD.setObjectName("ledBD")
        self.ledUsuario = QtWidgets.QLineEdit(self.gbxConexionBD)
        self.ledUsuario.setGeometry(QtCore.QRect(130, 80, 171, 20))
        self.ledUsuario.setObjectName("ledUsuario")
        self.ledContrasena = QtWidgets.QLineEdit(self.gbxConexionBD)
        self.ledContrasena.setGeometry(QtCore.QRect(130, 110, 171, 20))
        self.ledContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ledContrasena.setObjectName("ledContrasena")
        self.pbuConectar = QtWidgets.QPushButton(self.gbxConexionBD)
        self.pbuConectar.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pbuConectar.setObjectName("pbuConectar")
        self.labServidor = QtWidgets.QLabel(self.gbxConexionBD)
        self.labServidor.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.labServidor.setObjectName("labServidor")
        self.labBD = QtWidgets.QLabel(self.gbxConexionBD)
        self.labBD.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.labBD.setObjectName("labBD")
        self.LabUsuario = QtWidgets.QLabel(self.gbxConexionBD)
        self.LabUsuario.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.LabUsuario.setObjectName("LabUsuario")
        self.labContrasena = QtWidgets.QLabel(self.gbxConexionBD)
        self.labContrasena.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.labContrasena.setObjectName("labContrasena")
        self.gbxSeleccionTabla = QtWidgets.QGroupBox(self.ctrlWidget)
        self.gbxSeleccionTabla.setGeometry(QtCore.QRect(20, 169, 491, 191))
        self.gbxSeleccionTabla.setObjectName("gbxSeleccionTabla")
        self.labEsquema = QtWidgets.QLabel(self.gbxSeleccionTabla)
        self.labEsquema.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.labEsquema.setObjectName("labEsquema")
        self.labTabla = QtWidgets.QLabel(self.gbxSeleccionTabla)
        self.labTabla.setGeometry(QtCore.QRect(210, 20, 47, 13))
        self.labTabla.setObjectName("labTabla")
        self.lstEsquema = QtWidgets.QListWidget(self.gbxSeleccionTabla)
        self.lstEsquema.setGeometry(QtCore.QRect(20, 40, 181, 141))
        self.lstEsquema.setObjectName("lstEsquema")
        self.lstTabla = QtWidgets.QListWidget(self.gbxSeleccionTabla)
        self.lstTabla.setGeometry(QtCore.QRect(210, 40, 261, 141))
        self.lstTabla.setObjectName("lstTabla")
        self.pbaGeneraCSV = QtWidgets.QProgressBar(self.ctrlWidget)
        self.pbaGeneraCSV.setGeometry(QtCore.QRect(30, 460, 321, 21))
        self.pbaGeneraCSV.setProperty("value", 24)
        self.pbaGeneraCSV.setObjectName("pbaGeneraCSV")
        self.pbuGeneraCSV = QtWidgets.QPushButton(self.ctrlWidget)
        self.pbuGeneraCSV.setGeometry(QtCore.QRect(380, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pbuGeneraCSV.setFont(font)
        self.pbuGeneraCSV.setObjectName("pbuGeneraCSV")
        self.gbxConfiguraCSV = QtWidgets.QGroupBox(self.ctrlWidget)
        self.gbxConfiguraCSV.setGeometry(QtCore.QRect(20, 370, 491, 71))
        self.gbxConfiguraCSV.setObjectName("gbxConfiguraCSV")
        self.ledRuta = QtWidgets.QLineEdit(self.gbxConfiguraCSV)
        self.ledRuta.setGeometry(QtCore.QRect(90, 30, 351, 20))
        self.ledRuta.setObjectName("ledRuta")
        self.labRuta = QtWidgets.QLabel(self.gbxConfiguraCSV)
        self.labRuta.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.labRuta.setObjectName("labRuta")
        MainWindow.setCentralWidget(self.ctrlWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pbuConectar.clicked.connect(self.gbxConexionBD.update)
        self.lstEsquema.itemClicked['QListWidgetItem*'].connect(self.gbxSeleccionTabla.update)
        self.pbuConectar.clicked.connect(self.lstEsquema.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "table2csv - Exporta tabla a csv"))
        self.gbxConexionBD.setTitle(_translate("MainWindow", "Conexión Base de Datos"))
        self.pbuConectar.setText(_translate("MainWindow", "Conectar"))
        self.labServidor.setText(_translate("MainWindow", "Servidor:"))
        self.labBD.setText(_translate("MainWindow", "Base de datos:"))
        self.LabUsuario.setText(_translate("MainWindow", "Usuario:"))
        self.labContrasena.setText(_translate("MainWindow", "Contraseña"))
        self.gbxSeleccionTabla.setTitle(_translate("MainWindow", "Selección de Tabla"))
        self.labEsquema.setText(_translate("MainWindow", "Esquema:"))
        self.labTabla.setText(_translate("MainWindow", "Tabla:"))
        self.pbuGeneraCSV.setText(_translate("MainWindow", "Generar CSV"))
        self.gbxConfiguraCSV.setTitle(_translate("MainWindow", "Configuración CSV"))
        self.labRuta.setText(_translate("MainWindow", "Ruta:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

